---
- ansible.builtin.import_tasks: install_pip.yml
- ansible.builtin.import_tasks: download_gonka_git.yml
- ansible.builtin.import_tasks: generate_config.yml
- ansible.builtin.import_tasks: pull_docker_images.yml
- ansible.builtin.import_tasks: launch_node.yml

- name: "3. Complete Key Setup and Host Registration: https://gonka.ai/host/quickstart/#3-complete-key-setup-and-host-registration"
  ansible.builtin.debug:
    msg: |
      The following steps are better done manually on the network node:
        • Complete Key Setup and Host Registration (step 3)
      Connect to the host and run the required commands there, or run playbooks network/register and network/launch sequentially.

      SSH:
        ssh {{ ansible_user | default('root') }}@{{ ansible_host | default(inventory_hostname) }}
